version: '3.4'

services:
  cache:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: game_items_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  db_data:
  postgres_data:
